### PR TITLE
clean gitignore

### PR DESCRIPTION
**Pull request by benoitc**
people should be encouraged to use a global gitignore file.
https://help.github.com/articles/ignoring-files/

related to #1007

### CODE REVIEW

**Comment by berkerpeksag** [comment]
*.gem, *#*, .svn/, .DS_Store and .Python can be removed too.

**Comment by benoitc** [comment]
@berkerpeksag  removed other patterns (also rebased the changes). Should be be OK now, let me know.

**Comment by berkerpeksag** [comment]
LGTM (not sure what setuptools-* is for, but I think it can be removed too)

**Comment by benoitc** [comment]
can't remember, but think it was needed during testing ... let's keep it
for now :)

**Comment by GMLudo** [comment]
Don't forget the main goal of `.gitignore` is to avoid that somebody makes a pull request with wrong/personal content.
I'm not a Mac user, however, it should be newcomer friendly to keep `.DS_Store` to avoid mistakes from people that don't aware about global gitignore.

**Comment by benoitc** [comment]
I would rather solve that in a short developer documentation. would it be
enough?

**Comment by tilgovi** [comment]
We'll find out if we get PRs from people with .DS_Store files. :)

**Comment by benoitc** [comment]
indeed :)

**Pull request merged**
