### PR TITLE
Use suppress

### PR DESCRIPTION
**Pull request by blablatdinov**
This PR refactors the `Arbiter.reload` method in `gunicorn/arbiter.py` to utilize `contextlib.suppress` for handling KeyError exceptions, replacing the previous try-except block.

This change improves code readability and aligns with best practices for exception handling in Python.

### CODE REVIEW

**Comment by blablatdinov** [comment]
@benoitc take a look please

**Comment by benoitc** [comment]
I fail to see how using this context handler makes the code more readable. To which best practice are you referring?

**Comment by blablatdinov** [comment]
@benoitc Thanks for comment

You can show this page: [suppressible-exception](https://docs.astral.sh/ruff/rules/suppressible-exception/#suppressible-exception-sim105)

**Comment by benoitc** [comment]
i don't see any real addition in using this context there since it would slow down slightly the process. CLOSING as won't do. But thanks for the patch !

**Pull request closed without merging**
