### PR TITLE
Fix NameError fileno in gunicorn.http.wsgi

### PR DESCRIPTION
**Pull request by tuco86**
when fixing the fileno for BytesIO, actually setting fileno has been forogtten

tests said: 131 passed, 46 skipped

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Thanks!

**Comment by benoitc** [comment]
no please no :) this is a fake fileno that can't be used by sendfile(2). this shouldn't be merged. i am not at my desk right now, can you revert it?

**Comment by benoitc** [comment]
@berkerpeksag can you take care of a release? I'm not at my desk right now and will only be able to do it  later tonight.

**Comment by berkerpeksag** [comment]
@benoitc I can do a release tomorrow morning if you think the patch is OK.

**Comment by raphaelm** [comment]
Thanks for resolving this such quickly!

**Comment by benoitc** [comment]
@berkerpeksag just did it. Thanks anyway :)

**Comment by benoitc** [comment]
@tuco86 @raphaelm release is now available.

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
