### PR TITLE
[WIP] Add support for named constants in the --ssl-version flag

### LINKED ISSUE #1114: Add support for named constants in the --ssl-version flag
I'm using gunicorn with ssl cert and key. It provides TLS connection 1.0. Is it possible to configure gunicorn to use TLS 1.2?

### PR DESCRIPTION
**Pull request by berkerpeksag**
Fixes #1114

### CODE REVIEW

**Comment by tilgovi** [comment]
This looks good. Anything still need to be done?

**Comment by berkerpeksag** [comment]
I still need to update the documentation and add some more test cases. Hopefully I will have some time to do them this weekend.

**Comment by benoitc** [comment]
@berkerpeksag , wondering if it can be done sometimes next week for a new release. Let me know :)

**Comment by berkerpeksag** [comment]
@benoitc can you give me one more week? :)

**Comment by javabrett** [comment]
This looks good, but see also #1680 and comment in #1114.  A lot of these named-constants are now deprecated and use of options is recommended to provide exact protocol version control.

**Comment by javabrett** [comment]
As mentioned above, the Python `ssl.PROTOCOL_` constants have been a bit of a moveable-feast and subject to addition, deprecation etc.  I looked at the approach of using my `ssl.PROTOCOL_*` attribute-discovery, so that Gunicorn is more isolated from further changes, and any `PROTOCOL_` should be configurable by stripping-off that header.  Eventually these are going to be replaced by versionless-constants and `Options`.

I have:

- Rebased this PR branch and resolved the conflict.
- Added commits to:
  - Change the discovery mechanism for protocols to find all `ssl.PROTOCOL_*`.
  - Parametrized the test and tested all protocols for Python 2/3.
  - Added docs.

If this looks helpful, feel free to reset the PR branch to my branch [javabrett:ssl-version-named-contants](https://github.com/javabrett/gunicorn/tree/ssl-version-named-contants) and continue.

**Comment by tilgovi** [comment]
Thanks, @javabrett. That looks great.

**Comment by berkerpeksag** [comment]
Superseded by PR #1890.

**Pull request closed without merging**
