### PR TITLE
#1590 Use warnings module to state deprecations

### PR DESCRIPTION
**Pull request by Code0x58**

### CODE REVIEW

**Comment by Code0x58** [comment]
*cleaning up* I'm not inclined to add a test for this, even a shill to increase coverage. Can this be reviewed and the coverage bypassed if passed?

**Comment by benoitc** [comment]
Do we really need to tell the version ? For me it suffices to say it will be deprecated. So the plan can be changed...

**Comment by Code0x58** [comment]
Not necessarily, I would have been imitating Django's codebase which supports their [policy](https://docs.djangoproject.com/en/dev/internals/release-process/#deprecation-policy).

**Comment by berkerpeksag** [comment]
https://github.com/benoitc/gunicorn/issues/1590 has already been closed. Thank you for the PR!

**Pull request closed without merging**
