### PR TITLE
"work" -> "worker"

### PR DESCRIPTION
**Pull request by MichaelMBishop**

### CODE REVIEW

**Comment by tilgovi** [comment]
Thank you!

**Comment by berkerpeksag** [comment]
@MichaelMBishop could you also update the following line? :) https://github.com/benoitc/gunicorn/blob/master/gunicorn/config.py#L689 `docs/source/settings.rst` is generated from `gunicorn/config.py`.

**Comment by tilgovi** [comment]
😞 I knew that and I should have caught it. My apologies.

**Comment by berkerpeksag** [comment]
@tilgovi I keeping forgetting that too :) Perhaps it's time to make settings.rst the canonical place for documenting the Gunicorn settings?

**Comment by MichaelMBishop** [comment]
ok, @berkerpeksag so I'll update https://github.com/benoitc/gunicorn/blob/master/gunicorn/config.py#L689 ?

**Pull request merged**
