### PR TITLE
Solving issue #2692

### PR DESCRIPTION
**Pull request by hazho**
ValueError: count must be a positive integer (got 0)

### CODE REVIEW

**Comment by benoitc** [comment]
Thanks for the patch!

**Comment by mdeshmu** [comment]
when can this be released ?

**Comment by philicious** [comment]
@benoitc could you release a new version of gunicorn, containing this fix ?  thx !

**Comment by mdeshmu** [comment]
@benoitc when can this be released?

**Comment by hazho** [comment]
maybe @davisp or @tilgovi can answer those questions

**Comment by benoitc** [comment]
this will be released when ready for release. It's worked on.

**Pull request merged**
