### PR TITLE
Migrate to pyproject toml

### PR DESCRIPTION
**Pull request by deronnax**
It's 2023 and the future is pyproject.toml 🎉

### CODE REVIEW

**Comment by deronnax** [comment]
@benoitc can I have a CI run please 🙂 ?

**Comment by benoitc** [comment]
Thanks for the patch. can you describe what's supported in this PR?

**Comment by benoitc** [comment]
Hi thanks for your comment. I'm not a fan such file format, but let's follow the trend :) Thanks for the PR!

**Comment by deronnax** [comment]
Thank you for the merge 🙂

**Comment by deronnax** [comment]
Arg, I see an error slept in: the `license` string is incorrect, could you please apply this fix?
```diff
diff --git a/pyproject.toml b/pyproject.toml
index ec64a328..f4afa721 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -71,7 +71,7 @@ addopts = "--assert=plain --cov=gunicorn --cov-report=xml"
 [tool.setuptools]
 zip-safe = false
 include-package-data = true
-license-files = ["['LICENSE']"]
+license-files = ["LICENSE"]

 [tool.setuptools.packages]
 find = {namespaces = false}
```

Or I can make a PR if you want.

**Pull request merged**
