### PR TITLE
Separate Instrumentation and Logging

### PR DESCRIPTION
**Pull request by ykusakabe**
Proposed fix for #1564 on separation of instrumentation from logging by dynamically wrapping instrumentation methods and logging methods.
This allows multiple instrumentation possible if desired, loading from newly added config property, `instrumentation_classes`.

### CODE REVIEW

**Comment by benoitc** [comment]
why closing it?

**Comment by ykusakabe** [comment]
Ah sorry I forgot some backporting codes and caused build/test fail.
I was going to fix and re-create the pull request.

**Comment by benoitc** [comment]
np just wondered :) in any case we can always rebase or stash if it helps

**Comment by ykusakabe** [comment]
I opened another PR and did necessary rebase there.
Thanks @benoitc :)

**Pull request closed without merging**
