### PR TITLE
force astroid to version >= 1.5.0

### LINKED ISSUE #1674: travis issue with python 3.6: ERROR:   lint: commands failed
Does anyone know what is the issue on travis:

```bash

0.01s$ source ~/virtualenv/python3.6/bin/activate
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.11s$ Installing caching utilities
0.01s
7.79sattempting to download cache archive
fetching master/cache-linux-trusty-886521dd26aa2aaa6e97504d1d7c4758ce511240339b27af9468f9899b2c7fb2--python-3.6.tgz
found cache
0.01s
4.52sadding /home/travis/build/benoitc/gunicorn/.tox to cache
creating directory /home/travis/build/benoitc/gunicorn/.tox
adding /home/travis/.cache/pip to cache
$ python --version
Python 3.6.3
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (python 3.6)
install
1.89s$ pip install tox
Collecting tox
  Using cached tox-2.9.1-py2.py3-none-any.whl
Requirement already satisfied: pluggy<1.0,>=0.3.0 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from tox)
Collecting virtualenv>=1.11.2; python_version != "3.2" (from tox)
  Using cached virtualenv-15.1.0-py2.py3-none-any.whl
Requirement already satisfied: py>=1.4.17 in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from tox)
Requirement already satisfied: six in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages (from tox)
Installing collected packages: virtualenv, tox
Successfully installed tox-2.9.1 virtualenv-15.1.0
63.16s$ tox --recreate
lint recreate: /home/travis/build/benoitc/gunicorn/.tox/lint
lint installdeps: prospector
lint develop-inst: /home/travis/build/benoitc/gunicorn
lint installed: astroid==1.6.0,dodgy==0.1.9,flake8==3.5.0,flake8-polyfill==1.0.2,-e git+https://github.com/benoitc/gunicorn.git@5c9209321957b81645a789c0f89b0b7322cb62e9#egg=gunicorn,isort==4.2.15,lazy-object-proxy==1.3.1,mccabe==0.6.1,pep8-naming==0.5.0,prospector==0.12.7,pycodestyle==2.0.0,pydocstyle==2.1.1,pyflakes==1.6.0,pylint==1.8.1,pylint-celery==0.3,pylint-common==0.2.5,pylint-django==0.7.2,pylint-flask==0.5,pylint-plugin-utils==0.2.6,PyYAML==3.12,requirements-detector==0.5.2,setoptconf==0.2.0,six==1.11.0,snowballstemmer==1.2.1,wrapt==1.10.11
lint runtests: PYTHONHASHSEED='905328539'
lint runtests: commands[0] | prospector
Messages
========
.
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised)
Check Information
=================
         Started: 2018-01-07 17:24:47.307579
        Finished: 2018-01-07 17:25:25.881429
      Time Taken: 38.57 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, no_doc_warnings, no_member_warnings, strictness_medium, strictness_high, strictness_veryhigh
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, profile-validator, pylint
  Messages Found: 1
ERROR: InvocationError: '/home/travis/build/benoitc/gunicorn/.tox/lint/bin/prospector'
___________________________________ summary ____________________________________
ERROR:   lint: commands failed
The command "tox --recreate" exited with 1.
cache.2
store build cache
0.01s
7.08schange detected (content changed, file is created, or file is deleted):
/home/travis/build/benoitc/gunicorn/.tox/lint/bin/flake8
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_attrs.cpython-36.pyc
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_builtin_inference.cpython-36.pyc
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_collections.cpython-36.pyc
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_curses.cpython-36.pyc
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_dateutil.cpython-36.pyc
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_fstrings.cpython-36.pyc
/home/travis/build/benoitc/gunicorn/.tox/lint/lib/python3.6/site-packages/astroid/brain/__pycache__/brain_functools.cpython-36.pyc
/home/travis/build/benoitc
...
changes detected, packing new archive
uploading archive
after_script
$ if [ ! -f coverage.xml ]; then
      echo "No coverage.xml found; skipping sending coverage to couverture.io"
      return
  fi
  if [ $TRAVIS_PULL_REQUEST != false ]; then
      REAL_COMMIT=$(git log -n 1 $TRAVIS_COMMIT_RANGE --format="%H")
      PR_NUM=$TRAVIS_PULL_REQUEST
  else
      REAL_COMMIT=$TRAVIS_COMMIT
  fi
  curl \
      --verbose \
      --header "X-Couverture-Pull-Request: $PR_NUM" \
      --data-binary @coverage.xml \
      "https://app.couverture.io/coverage/github/benoitc/gunicorn/$REAL_COMMIT/$TOXENV"
  
No coverage.xml found; skipping sending coverage to couverture.io
Done. Your build exited with 1.
```

https://travis-ci.org/benoitc/gunicorn/jobs/326093059

(manual link from this not so modern travis ci)

### PR DESCRIPTION
**Pull request by benoitc**
fix #1674

### CODE REVIEW

**Comment by tilgovi** [comment]
Even though I just hit "approve", I realize after reading more the issue that it might not work. I think tox will install these both at the same time, which will error?

We might need to use custom tox install steps rather than `deps`.

**Comment by tilgovi** [comment]
If we have separate install steps for tox then we can call `pip` ourselves once to install prospector and then once to override the pin by installing a newer astroid, maybe?

**Comment by tilgovi** [comment]
Alternatively, can we disable lint on Python 3.6 until prospector is fixed?

**Comment by berkerpeksag** [comment]
> Alternatively, can we disable lint on Python 3.6 until prospector is fixed?

Python 3.5 is broken too: https://travis-ci.org/benoitc/gunicorn/jobs/326545817

**Comment by berkerpeksag** [comment]
> Python 3.5 is broken too: https://travis-ci.org/benoitc/gunicorn/jobs/326545817

Same for Python 3.4.

I suggest using pylint directly and drop prospector.

**Comment by tilgovi** [comment]
Fine for me.

**Comment by berkerpeksag** [comment]
Superseded by PR #1678.

**Pull request closed without merging**
