### PR TITLE
Make option to add new extra files with extension.

### PR DESCRIPTION
**Pull request by firekim2**
Make option to add new extra files with extension.

For example gunicorn ... --reload-extra-extension html
then, it watch and reload all *.html files.

### CODE REVIEW

**Comment by firekim2** [comment]
With small change, I can get directory for adding to list or regex type also.

**Comment by firekim2** [comment]
@berkerpeksag agree with that. I'll change it and commit it soon.

**Comment by firekim2** [comment]
I fixed code as you said. It works like these : 
--reload-extra-file path/to/somewhere/* : using * 
--reload-extra-file path/to/somewhere/a.html path/to/another/b.html : spacing

**Comment by benoitc** [comment]
what is the usage for it?

**Comment by firekim2** [comment]
This is for adding reload files simply.
If I try to adding whole templates folder for reload now, i should adding file by file like below:
--reload-extra-file path-to/file1 --reload-extra-file path-to/file2 ....
Buy with this change i can add directory or specific files in direcotry at once(for example: path-to/*.html)

**Comment by firekim2** [comment]
This is for adding reload files simply.
If I try to adding whole templates folder for reload now, i should adding file by file like below:
--reload-extra-file path-to/file1 --reload-extra-file path-to/file2 ....
But with this change i can add directory or specific files in direcotry at once(for example: path-to/*.html)

**Comment by tilgovi** [comment]
Something seems wrong... when I look at the changes now in the GitHub interface I only see changes to the config module (and two .DS_Store files added).

**Comment by firekim2** [comment]
Got it I'll reupload request. Thanks!

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to repost an updated PR as requested if needed.

**Pull request closed without merging**
