### PR TITLE
Reading Django's settings-file to get variables to Gunicorn

### PR DESCRIPTION
**Pull request by femesq**
As we talked on issue #1086, this is my first PR ever. Hope I did it the right way, and if not the code itself at least the idea could help someone.

### CODE REVIEW

**Comment by benoitc** [comment]
Looks good for me. Can you rebase your changes in one commit and resend(force) the PR?

**Comment by femesq** [comment]
Followed this steps (https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) but seens that didn't turned all commits  in one unique. Any tutorial on this to recommend? :flushed:

**Comment by berkerpeksag** [comment]
I don't think we need subprocess here. You can use something like https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/base.py#L85 then use it like `django_settings['DEBUG']`.

**Comment by berkerpeksag** [comment]
I'm using the following command to rebase and squash commits:

```sh
$ git rebase -i HEAD~N 
# N means total commits here. In our case it's 5 
# see https://github.com/benoitc/gunicorn/pull/1089/commits

# keep the first commit untouched and change others to "fixup"
# save and quit
$ git push -f origin your-branch-name
```

**Comment by benoitc** [comment]
@berkerpeksag good idea. 

@femesq are you still interested in making the change? Don't worry too much much about rebasing, we can make it at the end. Just let me know :)

**Comment by femesq** [comment]
@benoitc Yes, I'm still interested. Will try it again... :)

**Comment by benoitc** [comment]
bump.

**Comment by benoitc** [comment]
@femesq ping

**Comment by femesq** [comment]
Really really sorry about the delay on this...
I'm new to git... and even newer to github... 😜

Had deleted the previous fork and done it all over again... Hope this works
now...

Please let me know if there is any action that I must take to proceed...

Thanks,

**Comment by berkerpeksag** [comment]
Superseded by https://github.com/benoitc/gunicorn/pull/1207.

**Pull request closed without merging**
