### PR TITLE
statsd over a unix domain socket

### LINKED ISSUE #2066: Add option to report stats over a unix domain socket
I have a setup where DataDog's **statsd** agent listens on a **unix domain socket** (as opposed to a network UDP). Reasons for using UDS are listed [here](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/)

It would be useful if gunicorn allowed me to report its statsd metrics in such a setup.

### PR DESCRIPTION
**Pull request by wmalinowski**
Fixes #2066 
Adds a possibility of reporting statsd metrics over a unix domain socket

### CODE REVIEW

**Comment by wmalinowski** [comment]
I have run gunicorn with the new option for approx 3 weeks in production and had no problems with it

**Comment by tilgovi** [comment]
How would you feel about implementing this without a new setting? There is a function, `gunicorn.util.parse_address` that can be used to parse an address like `unix:///var/run/syslog.sock` (for example).

It returns a tuple of `(host, port)` for inet addresses and a string for UNIX socket paths.

**Comment by YueHonghui** [comment]
Good feature, waiting for it, any updates?

**Comment by larribas** [comment]
Is there any way I can help getting this PR ready and merged? Who do I need to bribe? :P

**Comment by wmalinowski** [comment]
> Is there any way I can help getting this PR ready and merged? Who do I need to bribe? :P

You don't need to bribe anyone 🙂 but I believe you would need to introduce the changes requested above by @tilgovi 
My priorities at work changed and I no longer work on a gunicorn app, so I don't even have a chance to make and test the changes.

**Comment by larribas** [comment]
hehe. I'd be happy to make those changes on top of what you've done.

@tilgovi when you said "without a new setting", what did you have in mind? Reusing the `statsd_host` setting?

And in that case, wouldn't the name become a bit of a misfit?

```python
statsd_host = "unix:///var/run/datadog/some.socket"
```

I don't really have a strong opinion about it. I just think if we go for a URI approach, `_address` or `_uri` might be a better fit.

**Comment by tilgovi** [comment]
I'd love to see a version of this that doesn't add any setting, doesn't change any name, just makes it work with `unix:`. We can add configuration aliases or update their names in the future, but let's get the feature in.  The `gunicorn.util.parse_address` function should help.

**Comment by larribas** [comment]
@tilgovi check #2384 and let me know if there's anything you'd change

**Pull request merged**
