### PR TITLE
Make the gevent workers handle the usr1 signal by deferring to a new greenlet

### PR DESCRIPTION
**Pull request by ant1g**

### CODE REVIEW

**Comment by ant1g** [comment]
Any suggestion on how to test this?

**Comment by tilgovi** [comment]
I think this is fine. We don't have anything set up to test a worker receiving signals. We could construct a worker and mock some things, but this is simple to verify by reading and mirrors what we do for `quit`.

Would you mind adding the same to the eventlet worker and then we can merge this?

**Comment by ant1g** [comment]
Done! Let me know if anything else is needed!

**Comment by ant1g** [comment]
Hello,
Any chance for this to be merged soon?

Cheers

**Comment by tilgovi** [comment]
Done.

**Comment by johaven** [comment]
I have this problem too (uwsgi 2.0.18) (gevent 1.4.0):

```
gateway "uWSGI http 1" has been buried (pid: 3993)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 3991)...
Error in atexit._run_exitfuncs:
Tue Apr 28 18:28:38 2020 - stopping gevent signals watchers for worker 1 (pid: 3991)...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 726, in gevent._greenlet.Greenlet.join
Tue Apr 28 18:28:38 2020 - stopping gevent sockets watchers for worker 1 (pid: 3991)...
Tue Apr 28 18:28:38 2020 - main gevent watchers stopped for worker 1 (pid: 3991)...
goodbye to the gevent Hub on worker 1 (pid: 3991)
  File "src/gevent/_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 66, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
  File "src/gevent/_greenlet_primitives.py", line 67, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch_out
gevent.exceptions.BlockingSwitchOutError: Impossible to call blocking function in the event loop callback
mule 1 (pid: 3992) annihilated
worker 1 buried after 1 seconds
```

**Pull request merged**
