### PR TITLE
Log a warning when a worker was terminated due to a signal

### PR DESCRIPTION
**Pull request by aberres**
This happens for example when being OOM killed.

See #2215

### CODE REVIEW

**Comment by aberres** [comment]
@benoitc @tilgovi Similar to the just merged #2277 this is a change which could make people running Kubernetes workloads a tad happier. Otherwise it is pretty hard to monitor OOM situations.

**Comment by benoitc** [comment]
which signal are we talking?

**Comment by aberres** [comment]
> which signal to who are we talking?

Kill.

When you have set memory limits set in Kubernetes it can easily happen that a worker is shot down without any kind of logging. Restarting work nicely, it is just that having a log eases the post mortem.

**Comment by benoitc** [comment]
i would suggest to configure kubernetes to send a sigterm instead of a
sigkill signal instead. That way the worker will be terminated gracefully/

Also if you know your application will leak or use a lot of ram over the
time you should limit the number of connections a worker can accept until
it is killing itself.

**Comment by aberres** [comment]
Yeah, that's an ongoing discussion of it should not send a SIGKILL immediately. But not likely to be changed as I understood the issues I was looking at.

More often than not when this situation arises it is likely a  configuration issue and the requested memory should be increased.

Thanks a lot for the merge!

**Comment by tilgovi** [comment]
K8s does send TERM for normal shutdown, but OOM killer in Linux always sends KILL, I think.

**Comment by CodeOnCoffee** [comment]
@benoitc Why was this revered in: https://github.com/benoitc/gunicorn/commit/76f8da24cbb992d168e01bda811452bcf3b8f5b3

We have workers being silently OOMKilled in Kubernetes and would like to setup an alert based on the logs

**Comment by javabrett** [comment]
Due to reentrant logging calls when handling a signal during another logging call, as observed in https://github.com/benoitc/gunicorn/issues/2564.

**Pull request merged**
