### PR TITLE
add support for eventlets _AlreadyHandled object

### PR DESCRIPTION
**Pull request by stefaang**
fixes https://github.com/benoitc/gunicorn/issues/1210

### CODE REVIEW

**Comment by Hum4n01d** [comment]
Does this just silence the error?

**Comment by benoitc** [comment]
thanks for the patch.

but such changes must be done in the eventlet worker code since it's
specific to it.

What about catching an optional value set by the worker?

btw Wondering why the lib can't use the gunicorn way that provide a
consistent behaviour across worker and doesn't force the usage of eventlet
though...has it been discussed?

**Comment by stefaang** [comment]
@Hum4n01d The error was caused by an empty wsgi response on disconnect, due to a slightly different implementation of the _AlreadyHandled object. The goal of _AlreadyHandled is to raise a StopIteration exception to close the socket.
@benoitc I reworked this into a wrapper around self.wsgi by overloading self.load_wsgi in the geventlet worker. 
I'm not that familiar with the all the eventing projects... but this error was messing up my logs so I wanted a quick fix.

**Comment by Hum4n01d** [comment]
I don't totally get what you're saying but please merge it @benoitc

**Comment by benoitc** [comment]
@stefaang the change can be simpler imo,

so we check `ALREADY_HANDLED` there:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/async.py#L104

Instead we could check it using a function `is_already_handled`  that could be overriden by the worker. In the case of Eventlet it would check for both the gunicorn value and the eventlet value. Do you want to make the change?

**Comment by stefaang** [comment]
You're right, that's a better approach. I'll get around with another fix.

**Comment by Hum4n01d** [comment]
So can it be merged?

**Comment by tilgovi** [comment]
This looks good to me.

**Comment by benoitc** [comment]
merged. Thanks!

**Comment by Hum4n01d** [comment]
Yay! Now my logs won't be clogged up

**Comment by qwexvf** [comment]
Thank you for this fix <3

**Pull request merged**
