### PR TITLE
Terminology changes

### PR DESCRIPTION
**Pull request by TylerLubeck**
nitpicky, but I was reading through this and figured I'd update it

### CODE REVIEW

**Comment by tilgovi** [comment]
All this usage is common, gender-neutral, singular form. "The first maintainer" makes clear that the subject is a single, primary maintainer.

**Comment by benoitc** [comment]
maybe but I disagree with the usage of "them" as a neutral pronoun. I would prefer a phrasing that skip it.

**Comment by benoitc** [comment]
Hat about this phrasing:

> The first maintainer listed is the primary maintainer who is assigned the Pull Request. The primary maintainer can reassign  a Pull Resuest to others listed maintainers.

**Comment by tilgovi** [comment]
That's good, too!

**Comment by TylerLubeck** [comment]
Updated with the suggested phrasing. Thank you for taking a look at this!

**Comment by benoitc** [comment]
merged. Thanks!

**Pull request merged**
