### PR TITLE
docs: a warning for disk-backed --worker-tmp-dir #1305

### PR DESCRIPTION
**Pull request by fillest**

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Thanks for the PR! Perhaps http://docs.gunicorn.org/en/stable/faq.html#troubleshooting or somewhere else would be a better location for this. We can then add a link to the FAQ entry in `worker_tmp_dir` documentation. Also, `settings.rst` is an auto-generated file. You will need to edit `gunicorn/config.py`.

**Comment by JayH5** [comment]
Maybe worth mentioning that in some environments it's not always as straightforward to mount filesystems - e.g. inside Docker containers. Would be great if the heartbeat system could not use files.

**Comment by benoitc** [comment]
bump. @berkerpeksag what should we do? @JayH5 it's planned :)

**Comment by berkerpeksag** [comment]
If @fillest doesn't have time to address my comments, I can do it sometime next week.

**Comment by fillest** [comment]
I will try to allocate the time, sorry for the delays

**Comment by benoitc** [comment]
bump

**Comment by fillest** [comment]
Ok, I've moved it to faq.rst. But I'm not sure how to properly add a link to the FAQ - I mean, what url to use (or if there's some markup that should be used so that url will be generated)?

(Also it may be better to squash the commits on merging this PR.)

**Comment by berkerpeksag** [comment]
> (or if there's some markup that should be used so that url will be generated)?

Thanks for the updated PR. Yes, there is a markup for this: http://www.sphinx-doc.org/en/stable/markup/inline.html#role-ref

Also, it would be great if you wrap the lines at 80 characters.

**Comment by fillest** [comment]
done

**Comment by tilgovi** [comment]
Thanks!

**Pull request merged**
