### PR TITLE
Implement a metric that records the queuing time…

### LINKED ISSUE #2555: Add a metric for thread starvation
We are running a flask application with gunicorn which, when it's under load, suffers thread starvation without high CPU (it's an app that has a lot of IOWait on other services). It has been very challenging to monitor this, and also very difficult to do automatic scaling.

To sidestep this, I'm proposing a new statsd metric: it would monitor the amount of time that an incoming request spends in the gthread queue waiting for a worker thread to become available. This metric is the most reliable way for us to see if incoming requests are being queued and that we should scale up our deployments.

I'm filing this issue because the contribution guidelines suggested that I do so, but I'm preparing to submit #2554 for the implementation that we are using.

### PR DESCRIPTION
**Pull request by bsmedberg-xometry**
… between when we accept a connection and when a thread picks it up. This can detect situations where requests are backed up with thread starvation.

Fixes #2555

### CODE REVIEW

**Comment by bsmedberg-xometry** [comment]
@benoitc first time contributor to this project: please let me know if you need me to do something else! The linters are failing on changes unrelated to my own, so I'm not sure whether I need to worry about that.

**Comment by colincoghill** [comment]
Is there much that needs done to get this merged/mergeable? It'd be really useful for helping diagnose some problems, I think.

The test failures don't look related to the code change.

**Comment by bsmedberg-xometry** [comment]
I don't know what is required to take this over the finish line. My most recent commit should correct an error I discovered. @benoitc any suggestions would be appreciated!

**Comment by benoitc** [comment]
sorry please do it the log as a separate function . This will help to abstract the metrics engine.

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.

**Pull request closed without merging**
