### PR TITLE
Fix compatibility with latest eventlet

### PR DESCRIPTION
**Pull request by Boring-Mind**
Fix issue with import error while using latest eventlet (>=0.30.3).

Changes made in eventlet: https://github.com/benoitc/gunicorn/pull/2581

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks for the PR, intended to address #2582.

This is an alternative to the approach taken in #2581, which is meant to work with eventlet both before and after the change.

**Comment by Boring-Mind** [comment]
I'm also not sure that this code works but it gives a basic idea of how it would work.

**Comment by ozamani9** [comment]
while this incompatiabilty with eventlet version be released soon.  we need to upgrade eventlet to 0.31.0 to resolve the vulnerability.   very eager to find out when it will be available.

thanks
omid

**Comment by benoitc** [comment]
> Thanks for the PR, intended to address #2582.
> 
> This is an alternative to the approach taken in #2581, which is meant to work with eventlet both before and after the change. Based on the code there, I'm not sure that the code here is correct (or vice versa).

what do you mean ? This changes allows to handle the changes at load time instead of running a check every time so I would go for it. The only issue  to have with this changes is the need to clarify in the documentation that updating a dependency  like eventlet is like updating gunicorn and requires to send an USR2 signal.  Do you see any blocker vs the other proposal?

**Comment by benoitc** [comment]
> while this incompatiabilty with eventlet version be released soon. we need to upgrade eventlet to 0.31.0 to resolve the vulnerability. very eager to find out when it will be available.
> 
> thanks
> omid

did you test the patch? Any feedback about it would speed a release of course.

**Comment by temoto** [comment]
@Boring-Mind sorry, ALREADY_HANDLED from previous version and WSGI_LOCAL work in completely different way. It wasn't just a rename of variable.

**Comment by Boring-Mind** [comment]
@temoto no problems, I was happy to participate in the development and help to resolve that issue in any way.

**Comment by mgorny** [comment]
Thanks from Gentoo for the patch!

**Comment by benoitc** [comment]
> Thanks from Gentoo for the patch!

which patch?

**Comment by mgorny** [comment]
> > Thanks from Gentoo for the patch!
> 
> which patch?

I meant this pull request.

**Pull request closed without merging**
