### PR TITLE
Use the --install option instead of sudo.

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by tilgovi** [comment]
How reliably is the `--user` install bin going to be in the user's path?

**Comment by benoitc** [comment]
I have no ideas on what is doing this command, so I will trust you about it :)

**Comment by berkerpeksag** [comment]
> How reliably is the --user install bin going to be in the user's path?

No idea, but it's better than sudo anyway :)

**Comment by berkerpeksag** [comment]
Actually, we can just remove virtualenv lines.

```sh
$ pip install gunicorn
$ cat myapp.py
   def app(environ, start_response):
       data = b"Hello, World!\n"
       start_response("200 OK", [
           ("Content-Type", "text/plain"),
           ("Content-Length", str(len(data)))
       ])
       return iter([data])
$ gunicorn -w 4 myapp:app
```

looks simpler to me.

**Comment by benoitc** [comment]
+1

**Comment by tilgovi** [comment]
Sounds good to me. Virtualenv is the user's choice. We can add a note about virtualenv generally, pointing to a tutorial, if we want to.

**Comment by benoitc** [comment]
@berkerpeksag so let's go with out sudo then :)

**Comment by benoitc** [comment]
bump.

**Comment by tilgovi** [comment]
:+1: to removing virtualenv from the instructions.

**Comment by berkerpeksag** [comment]
I will update this today, thanks for the reviews!

**Pull request merged**
