### PR TITLE
[WIP] Delete all Python 2 compatibility code

### PR DESCRIPTION
**Pull request by berkerpeksag**
- [x] Delete argparse code
- [ ] Delete Python 2 compatibility code from `gunicorn/_compat.py`
- [ ] Consider deleting  `gunicorn.selectors`
- [ ] Delete `gunicorn/http/_sendfile.py`

### CODE REVIEW

**Comment by tilgovi** [comment]
Whoa! We going 3-only for 20+?

**Comment by berkerpeksag** [comment]
Yes :) https://github.com/benoitc/gunicorn/issues/1195

**Comment by benoitc** [comment]
@tilgovi Why?

But yes, like said on #1195 we don't drop the support of 2.x anyway. The 19.X branch will continue to receive updates but no more new features though some backports will be possible if requested. 

I think it's a good plan, anyway, maintaining 2 versions starts to be really difficult. Also it will allow us to give plain support for the async, asyncio APIS and such things.

**Comment by tilgovi** [comment]
All good!

**Comment by berkerpeksag** [comment]
FYI: I'm planning to add scripts to make backporting and release process
easier.

**Comment by tilgovi** [comment]
When would you all like to branch for 20?

**Comment by tilgovi** [comment]
I would love to branch 19 off any time we're ready.

**Comment by berkerpeksag** [comment]
Superseded by #1764.

**Pull request closed without merging**
