### PR TITLE
parse_syslog_addr sock_type default

### PR DESCRIPTION
**Pull request by guj-zz**
Default to sock_type None, unless explictly overridden, and explain how this covers both options

### CODE REVIEW

**Comment by tilgovi** [comment]
It sounds like this is correct, but I don't know. Can you point me to any documentation or code links in the syslog implementation?

**Comment by tilgovi** [comment]
Oh, right, this is #1530. I think this looks good.

**Comment by guj-zz** [comment]
Hello, Randall.

On 8/7/2017 2:14 AM, Randall Leeds wrote:
> tilgovi approved this pull request.

Thank you. In case this is needed for documentation purposes, the
comment I was referring to is in logging.py, currently at
https://github.com/python/cpython/blob/master/Lib/logging/handlers.py#L806
HTH

Sincerely,
Stephan

-- 

Gruner+Jahr AG & Co KG
Informationstechnologie
IT-Betrieb / Anwendungsservices
20459 Hamburg
Am Baumwall 11
Telephon +49-40-3703-3177

**Comment by tilgovi** [comment]
Thanks so much!

**Pull request merged**
