### PR TITLE
Fix on #2923 to address BaseException type in error handling 

### PR DESCRIPTION
**Pull request by min-tian-thomas**
See https://github.com/benoitc/gunicorn/issues/2923 for more context

### CODE REVIEW

**Comment by min-tian-thomas** [comment]
@benoitc any comments to this issue described #2923 ?

**Comment by PaulPabloo** [comment]
Can you give an update on the status of this pull request? We are seeing Gunicorn Zombie threads being created whenever any BaseException is thrown.

**Comment by baswelsh** [comment]
+1 Is there an updated release target for this?

**Comment by tilgovi** [comment]
Just for the record keeping, this was closed in 40232284934c32939c0e4e78caad1987c3773e08.
Thanks, all!

**Comment by min-tian-thomas** [comment]
WWelcom 👍🏻

**Pull request closed without merging**
