### PR TITLE
Fix auto reloader

### LINKED ISSUE #2339: reload does not work for uvicorn.workers.UvicornWorker
this is my commandline`
gunicorn -k uvicorn.workers.UvicornWorker --reload-engine=inotify   --workers=1 --log-level debug  --access-logfile - --error-logfile - --disable-redirect-access-to-syslog --reload  main:app`

note that i have tested with both master branch of gunicorn as well as last stable release.

This is the code im using
```

from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def read_root():
    # raise 1
    return {"Hello": "World"}


@app.get("/items/{item_id}")
async def read_item(item_id: int, q: str = None):

    return {"item_id 2": item_id, "q": q}

```

reload does not pickup when i make changes to the app. im using vscode as an editor

### LINKED ISSUE #2814: Not reloading Python modules when inside k3s+docker
Hi folks,

I'm not sure if this is a bug or if I'm doing something wrong, but I'm building a project where I need to run my app inside Kubernetes pods on my own computer, so I use k3s for that. However, I've set it up to reload my gunicorn instance running inside my pod, using `poll` as the reload engine (gave up using inotify, wasn't working reliably inside the pod), and, even though gunicorn says it detected file changes and is reloading the workers, they don't really seem to be reloaded, as I keep getting the same contents over and over.

To test this inside my app, which is basically a FastAPI-based API, I created an endpoint that provides me a certain JSON payload. Every time I change this payload, I see gunicorn saying it's reloading the modules, but if I hit the endpoint again I get the old payload back.

Maybe Gunicorn is caching something that I don't know? Do you guys see anything wrong in my approach?

Thanks!

### PR DESCRIPTION
**Pull request by bigsbug**
Auto-reloading with the Uvicron worker after detecting new changes produces the following issues: 
Fixes #2339
Fixes #2814

Also, I guess there are some issues with the auto-reload, such as:
#1562

There is a problem with using the sys.exit() in a forked process (child processes or workers) instead of using the os._exit() that is mentioned in [python documentation](https://docs.python.org/3/library/os.html#os._exit).

This modification solved the problem and passed all tests.

### CODE REVIEW

**Comment by bigsbug** [comment]
Hi, @brosner do you can review this PR and merge it?

**Comment by benoitc** [comment]
Changes looks good. I will check. I would rather prefer that python fix this. Has an issue been open upstream?

**Comment by bigsbug** [comment]
yes there has an open issue for it

**Comment by bigsbug** [comment]
Hi, @brosner, I checked this problem with different versions of python and the result are the same !!. and I also checked the documentation of several versions of python and all of them mentioned this situation.
I don't think it is an issue with python, and in the python upstream I can't find any related issue.
so what do you think?

**Comment by tilgovi** [comment]
I don't think I understand this PR. From what I read, it's frequently the case that a program may not want to close flush stdio or call exit handler from a child process, but does Gunicorn? I don't think we register any `atexit` handlers, but developers might do so in server hooks. Would they expect those to be called when a worker exits? I don't know. This would definitely be a change in behavior.

Do we have an explanation for why it solves the linked issues? I think that's what I'm missing. I'm not understanding the value, only the risk.

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.

**Pull request closed without merging**
