### PR TITLE
Update FAQ - Workers Silently Killed.

### PR DESCRIPTION
**Pull request by monobaila**
Fixes/Documents Issue 2215.

### CODE REVIEW

**Comment by tilgovi** [comment]
Looks good to me!

**Comment by benoitc** [comment]
merged. Thanks all :)

**Comment by rollokb** [comment]
@monobaila hey you mention in your merge request that you can configure the OOM to do something else rather than sigkill?

I'm searching for a way to configure this, andy inks?

**Comment by monobaila** [comment]
> @monobaila hey you mention in your merge request that you can configure the OOM to do something else rather than sigkill?
> 
> I'm searching for a way to configure this, any links?

I've had to read through again to remind myself. I'm afraid I think my wording was a bit clumsy here - It's possible to tell OOM killer not to "SIGKILL by default" - but they're not great alternatives which are system panic instead or disable oom killer, both pretty drastic actions. Their might have been some other possibility but I can't remember exactly. In hindsight this sentence just leads to confusion - apologies.

**Pull request merged**
