### PR TITLE
only the arbiter should unlink the unix socket

### LINKED ISSUE #1298: unix socket gets deleted on worker restart
We have a django app deployed on heroku with gunicorn 19.6.0
It is binding to a unix socket that's used by Nginx.

These are the options that we're using:

```
  --max-requests 500 \
  --max-requests-jitter 25 \
  --preload \
  --threads 2 \
  --timeout 27 \
  --workers 3 \
  --bind unix:/tmp/nginx.socket
```

What we're seeing is that the socket file disappears after a while.
Downgraded to gunicorn 19.4.5 and things are working fine.

Is the nginx socket file being deleted accidentally?

### PR DESCRIPTION
**Pull request by benoitc**
make unlink explicitly done by the arbiter.

 fix #1298

### CODE REVIEW

**Comment by diwu1989** [comment]
what if the unix socket was already created before gunicorn starts, for example, if another process like nginx created the socket first?

would gunicorn still try to unlink the unix socket?

**Comment by benoitc** [comment]
@diwu1989 normally yoou should start gunicorn first. we don't have yet a way to handle such case except when you're using systemd. Is the current patch working for you?

**Comment by tilgovi** [comment]
I'm noticing that because LISTEN_FDS doesn't get propagated this behavior is broken for systemd. If we were to more thoroughly refactor this, do you think we can make this work? I'm thinking that instead of managing this on the socket, we could a symmetric `close_sockets` function in the `sock` module with an `unlink` parameter.

In the arbiter:

```python

def reexec():
   # ... after fork ...
   if self.systemd:
       environ['LISTEN_PID'] = os.getpid()
   else:
        environ['GUNICORN_FD'] = ",".join([str(fd) for fd in fds])
        environ['GUNICORN_PID'] = str(master_pid)
    # ... and so on ...

def stop():
    unlink = self.reexec_pid == 0 and self.master_pid == 0 and not self.systemd
    close_sockets(self.LISTENERS, unlink=unlink)
```

**Comment by tilgovi** [comment]
We could parse the systemd environment cleanly, isolating this into a separate thing.

```python
# gunicorn.systemd module
import os

def listen_fds():
    if ('LISTEN_PID' in os.environ
            and int(os.environ.get('LISTEN_PID')) == os.getpid()):
    # ...
```

The arbiter could then keep all the `GUNICORN_FDS` logic, instead of the `sock` module. The arbiter checks for systemd sockets, sets `self.systemd`. Otherwise, it checks for fds in `GUNICORN_FDS`. If either are found, it passes these to `create_sockets`. The `create_sockets` function can use `getsockname()` and the difference between systemd and gunicorn inheritance goes away. The arbiter is now responsible for deciding whether gunicorn ultimately unlinks, by knowing where it got the fds.

**Comment by tilgovi** [comment]
Untested, but this is the sort of refactor I am thinking about: https://github.com/benoitc/gunicorn/compare/fix/1298-2

**Comment by benoitc** [comment]
@tilgovi I like the idea! Do you mind to create a PR for it? So we can comment the code directly :)

**Comment by tilgovi** [comment]
#1310 with tests

**Comment by tilgovi** [comment]
Could use additional tests for socket creation, especially inheritance and systemd activation. I only really added tests that assert unlink is done correctly.

**Comment by diwu1989** [comment]
just tested this out and it fixes our problem

**Comment by tilgovi** [comment]
@benoitc I don't mind landing this patch fix and deferring the bigger refactoring for R20.

**Comment by diwu1989** [comment]
hi, can this be release soon please?
thanks

**Comment by kaniini** [comment]
We hit this on 19.6 and had to downgrade to 19.4.5 to solve it.  This issue is causing many people's applications to break in strange ways because workers aren't being properly terminated causing all sorts of resource exhaustion issues.

I would say a release with this fix is critical.

**Comment by tilgovi** [comment]
Fixed by #1310

**Pull request closed without merging**
