### PR TITLE
Fix issue #1011

### PR DESCRIPTION
**Pull request by vlad-dragos**

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Looks good, thanks. Can you add a little bit more information to the commit message?

**Comment by vlad-dragos** [comment]
@berkerpeksag Should I change it using git commit --amend or should I create a new pull request?

**Comment by berkerpeksag** [comment]
Yes, `git commit --amend` is fine. No need to create a new PR.

**Comment by vlad-dragos** [comment]
Done

**Comment by vlad-dragos** [comment]
Somehow I closed the pull request by mistake.

**Comment by berkerpeksag** [comment]
Merged in https://github.com/benoitc/gunicorn/commit/342512a12868bc7dadbaf3c85b5aedd86bb990e7. Thanks! :)

**Pull request closed without merging**
