### PR TITLE
Update Debian and Ubuntu distribution information

### PR DESCRIPTION
**Pull request by kofrezo**
- Recommend latest (supported) Debian and Ubuntu versions
- Update provided versions of gunicorn in Debian and Ubuntu

### CODE REVIEW

**Comment by kofrezo** [comment]
Hey :wave:,
It is not much of a contribution but I felt like I can help you a little bit with updating these parts while reading it :-)

**Comment by tilgovi** [comment]
Thank you, this is great! There's a build failure for the docs linting, for some reason. Can you tell if that's spurious or real and whether there's anything to do?

**Comment by tilgovi** [comment]
Add, line 122 and line 144, you need to extend the underline. Sadly, reStructuredText is picky like that.

**Comment by kofrezo** [comment]
> Add, line 122 and line 144, you need to extend the underline. Sadly, reStructuredText is picky like that.

I see thanks for pointing me to the right lines. I adjusted them.

**Comment by kofrezo** [comment]
I added another commit where I adjusted the package name to `gunicorn3`. While Debian release newer than Stretch have a virtual package gunicorn3 which points to gunicorn with Python3 support for Stretch (oldstable) there is still a difference (Python2 vs Python3 version).

I think this makes it more clear which version one installs no matter with release one is using.

**Comment by tilgovi** [comment]
Very helpful. Thank you!

**Pull request merged**
