### PR TITLE
Add --print-config option to print the resolved configuration

### PR DESCRIPTION
**Pull request by rcoup**
Implementation of #2052. WIP for review.

### Sample output:
```console
$ gunicorn --print-config foo
access_log_format                 = %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
accesslog                         = None
backlog                           = 2048
bind                              = ['127.0.0.1:8000']
ca_certs                          = None
capture_output                    = False
cert_reqs                         = 0
certfile                          = None
chdir                             = /Users/rcoup/code/gunicorn
check_config                      = False
child_exit                        = <ChildExit.child_exit()>
ciphers                           = None
config                            = None
daemon                            = False
default_proc_name                 = foo
disable_redirect_access_to_syslog = False
do_handshake_on_connect           = False
dogstatsd_tags                    =
enable_stdio_inheritance          = False
errorlog                          = -
forwarded_allow_ips               = ['127.0.0.1']
graceful_timeout                  = 30
group                             = 20
initgroups                        = False
keepalive                         = 2
keyfile                           = None
limit_request_field_size          = 8190
limit_request_fields              = 100
limit_request_line                = 4094
logconfig                         = None
logconfig_dict                    = {}
logger_class                      = gunicorn.glogging.Logger
loglevel                          = info
max_requests                      = 0
max_requests_jitter               = 0
nworkers_changed                  = <NumWorkersChanged.nworkers_changed()>
on_exit                           = <OnExit.on_exit()>
on_reload                         = <OnReload.on_reload()>
on_starting                       = <OnStarting.on_starting()>
paste                             = None
pidfile                           = None
post_fork                         = <Postfork.post_fork()>
post_request                      = <PostRequest.post_request()>
post_worker_init                  = <PostWorkerInit.post_worker_init()>
pre_exec                          = <PreExec.pre_exec()>
pre_fork                          = <Prefork.pre_fork()>
pre_request                       = <PreRequest.pre_request()>
preload_app                       = False
print_config                      = True
proc_name                         = None
proxy_allow_ips                   = ['127.0.0.1']
proxy_protocol                    = False
pythonpath                        = None
raw_env                           = []
raw_paste_global_conf             = []
reload                            = False
reload_engine                     = auto
reload_extra_files                = []
reuse_port                        = False
secure_scheme_headers             = {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
sendfile                          = None
spew                              = False
ssl_version                       = 2
statsd_host                       = None
statsd_prefix                     =
suppress_ragged_eofs              = True
syslog                            = False
syslog_addr                       = unix:///var/run/syslog
syslog_facility                   = user
syslog_prefix                     = None
threads                           = 1
timeout                           = 30
tmp_upload_dir                    = None
umask                             = 0
user                              = 501
when_ready                        = <WhenReady.when_ready()>
worker_abort                      = <WorkerAbort.worker_abort()>
worker_class                      = sync
worker_connections                = 1000
worker_exit                       = <WorkerExit.worker_exit()>
worker_int                        = <WorkerInt.worker_int()>
worker_tmp_dir                    = None
workers                           = 1
```

### Todo: 

- [ ] review approach
- [x] tests
- [x] ci passing
- [x] docs
- [x] ~why doesn't on_exit print like the other callables?~

### Questions:

1. Currently printing the config happens _before_ `Application.load()` is called? Can/does config change during `load()`? (ie. should it happen afterwards?)
2. Currently printing the config also does `check_config`. Which means (a) it always exits afterwards, and (b) it actually validates things work. Personally that's sane behaviour, but opinions welcome
3. Should we include whether the value == the default? I can see it's kinda useful, but it could also be that you've _set_ it the same as the default, so people might waste time trying to debug that.

### CODE REVIEW

**Comment by rcoup** [comment]
Changes:

* Moved it to the Config object (as `__str__()`). Much tidier.
* Aligned output for reading
* Improved formatting
* Added a test
* Removed Py2-isms

(Would be good to backport if 19.x is still a supported branch?)

**Comment by Tecktron** [comment]
@benoitc Any progress on this? Have been really looking forward to this. Seems like it might need a rebase now tho.

**Comment by benoitc** [comment]
LGTM. please resolve the conflict :)

**Comment by tilgovi** [comment]
Merged with conflicts resolved and I kept two documentation blocks to instruct how to both print and check (without printing) the config. Thanks @rcoup!

**Comment by frerikandriessen** [comment]
I'm a bit late to the party, but I actually think being able to `print-config` and continue startup of your app would be nice. If I wanted to do a dry-run, I could combine `print-config` and `check-config`. 

I guess implementing it like that would now break functionality, but could we perhaps incorporate an optional value for `print-config` like `--print-config=continue-startup`? I would be willing to make a PR for this if you think it has merit.

**Comment by Davidrjx** [comment]
when exec  'gunicorn --print-config <app module>' on cmdline, is it possible to exit but not start app

**Pull request merged**
