### PR TITLE
fix: eventlet worker never calls monkey_patch()

### PR DESCRIPTION
**Pull request by xgfone**
The method `init_process()` of the parent worker will call the method `run()` in the end, but `run()` never exits until the worker is over. So we must call the method `patch()` before calling `init_process()` of the parent worker. Or `eventlet.monkey_patch()` is never called.

To refer to the gevent worker, calling `patch()` is before `init_process()`.

### CODE REVIEW

**Comment by xgfone** [comment]
Repeat

**Comment by benoitc** [comment]
?

**Comment by xgfone** [comment]
@benoitc I just see #1847. I think it has been fixed.

**Comment by xgfone** [comment]
Hasn't it been fixed? If that, Can I reopen this PR? @benoitc

**Comment by tilgovi** [comment]
Re-opening.

**Comment by tilgovi** [comment]
@benoitc could you check this one? If eventlet monkey patching is broken, we should fix it for R20.

**Comment by tilgovi** [comment]
I think the fix we need may be to reset the `SIGCHLD` handler after fork so that the workers are not catching it, by using `signal.signal(signal.SIGCHLD, signal.SIGDFL)`.

I understand from reading #1584 that Gunicorn was catching a `SIGCHLD`. Since the Eventlet worker calls `patch` before its base class calls `init_signals`, my only guess is that the `SIGCHLD` handler installed by the Arbiter is inherited across the `fork()` and maybe it needs to be cleared for Eventlet to initialize properly.

**Comment by colincadams** [comment]
Can this PR be merged as is? Without it, patching never happens.

**Comment by tilgovi** [comment]
@colincadams not until someone can explain an alternative way to address #1584, which is what c2757bd84152e0c2d5f659fa199509fa67e8469e tried to fix.

**Pull request closed without merging**
