### PR TITLE
Emphasize that full greenlet support might need additional work

### PR DESCRIPTION
**Pull request by aberres**
When I read about the async worker the first time I had no idea about greenlets and stuff.
I think it would have helped me to get some additional context as the async worker is obviously no silver bullet.

### CODE REVIEW

**Comment by benoitc** [comment]
we can add an expectation / workers imo

**Comment by tilgovi** [comment]
It's okay for me. I might take out context variables. I'm just thinking about what might be most likely to become out of date. Making specific recommendations is tricky.

**Comment by aberres** [comment]
I agree that the documentation might benefit from some additional context and maybe examples. At least for the moment I do not have the time to add anything else though.

I agree about not referencing context variables. I removed the clause.

**Comment by tilgovi** [comment]
This is great. Thank you for helping make the documentation better!

**Pull request merged**
