### PR TITLE
Revert "Tweaks"

### PR DESCRIPTION
**Pull request by benoitc**
Reverts benoitc/gunicorn#1589

### CODE REVIEW

**Comment by benoitc** [comment]
as spotted by @berkerpeksag this should be reverted

**Comment by tilgovi** [comment]
:+1:

**Comment by benoitc** [comment]
hrm  ok, so please do and close the pr :)

**Comment by berkerpeksag** [comment]
Reverted cbbafdb9b1f8b0f04c7a0d174b5d56962e6bdbfe in 1edf8fcff5cf19e1580a927b10acdedbda2152a0.

**Pull request closed without merging**
