### PR TITLE
Fix socketfromfd

### LINKED ISSUE #2201: 20.0.2 raise OSError
I use `kill -USR2 ` to reload process, but it raise error.

```
[2019-11-25 11:33:44 +0800] [3967] [INFO] Starting gunicorn 20.0.2
[2019-11-25 11:33:44 +0800] [3967] [INFO] Listening at: http://127.0.0.1:8000 (3967)
[2019-11-25 11:33:44 +0800] [3967] [INFO] Using worker: sync
[2019-11-25 11:33:44 +0800] [3970] [INFO] Booting worker with pid: 3970
[2019-11-25 11:33:51 +0800] [3967] [INFO] Handling signal: usr2
[2019-11-25 11:33:51 +0800] [3975] [INFO] Starting gunicorn 20.0.2
Traceback (most recent call last):
  File "/Users/xx/project/py37/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/app/base.py", line 219, in run
    super().run()
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/arbiter.py", line 198, in run
    self.start()
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/arbiter.py", line 155, in start
    self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/sock.py", line 171, in create_sockets
    sock = fromfd(fd)
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/socketfromfd.py", line 95, in fromfd
    family = _raw_getsockopt(fd, socket.SOL_SOCKET, SO_DOMAIN)
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/socketfromfd.py", line 74, in _raw_getsockopt
    ctypes.byref(optval), ctypes.byref(optlen))
  File "/Users/xx/project/py37/lib/python3.7/site-packages/gunicorn/socketfromfd.py", line 44, in _errcheck_errno
    raise OSError(errno, os.strerror(errno))
OSError: [Errno 42] Protocol not available

```

### PR DESCRIPTION
**Pull request by benoitc**
fix cases where the type of socket is not correctly detected on mac.

fix #2201

### CODE REVIEW

**Comment by benoitc** [comment]
we can also probably just use the python method directly on python >= 3.8 , what do you think?

**Comment by jamadden** [comment]
In Python 3.5 and 3.6, the `socket.socket` documentation says that " the values for *family*, *type*, and *proto*" are ignored when a *fileno* is given. In 3.7, that text was changed to explicitly state:

>  the values for *family*, *type*, and *proto* are auto-detected from the specified file descriptor. Auto-detection can be overruled by calling the function with explicit family, type, or proto arguments. **This only affects how Python represents e.g. the return value of socket.getpeername() but not the actual OS resource**.

All versions document `fromfd` with "Address family, socket type and protocol number are as for the socket() function."

So I would think that on 3.7 and above we could skip all of our auto-detection and let Python handle it. (The less ctypes, the better!) `return socket.socket(fileno=fd)`

Maybe we could skip it everywhere since they're documented as being ignored? I haven't looked at why gunicorn is doing this. (`fromfd` doesn't have defaults for those three arguments so we could either `dup()` the `fd` ourself and call `socket.socket()`, or pass in default values to be ignored.)

**Comment by benoitc** [comment]
@jamadden I agree, but I'm not sure for 3.5, 3.6. In doubt i would just use python `fromfd` on python >+ 3.7 and continue to use this change for now.   I think the main reason for it was to make sure the new y created socket was using the correct class.

**Comment by benoitc** [comment]
@jamadden the proto and type are the default used by python if none is set, only the family seems to be the mandatory, so this PR seems to be right.

**Comment by benoitc** [comment]
reading https://bugs.python.org/issue28134  it seems that this module is needed since autodetection is not working on python =< 3.7 alsowe need to make sure to keep the fd around which is only guaranted using fromfd.

**Comment by jamadden** [comment]
Ah, I forgot about that Python bug. So yeah, this looks good for Python <= 3.6.

**Pull request merged**
