### PR TITLE
add info about contributions in readme

### PR DESCRIPTION
**Pull request by LeonardoFurtado**
Adding a link to your contribution guide in the README. I think this helps new users find this easily.

### CODE REVIEW

**Comment by benoitc** [comment]
thanks!

**Comment by tilgovi** [comment]
Was this merged?

**Comment by LeonardoFurtado** [comment]
Apparently no

**Comment by tilgovi** [comment]
I'm assuming you closed it by accident then, and I've re-opened it.

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
