### PR TITLE
Unreader unit tests

### PR DESCRIPTION
**Pull request by irvind**
In this PR I added unit tests for Unreader and its subclasses. Also I fixed `recv` method of `FakeSocket` because it doesn't use `length` argument.

### CODE REVIEW

**Comment by berkerpeksag** [comment]
This is great! :) Thanks for writing tests :)

**Comment by irvind** [comment]
Added a little bit more tests.

**Comment by berkerpeksag** [comment]
Looks good to me, thanks!

**Comment by berkerpeksag** [comment]
I'm merging this since @tilgovi already gave a :+1:. Thanks again, @irvind. I hope you'll continue to improve our test coverage :)

**Pull request merged**
