### PR TITLE
Raise InvalidRequestLine instead of ValueError if the line contains m…

### LINKED ISSUE #1023: Gunicorn fails with a 500, instead of a 400, when a request path is a malformed IPv6 address
Request:

```
~/.v/tempenv-701523535780 $ telnet localhost 8000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
PUT ///]ufd/: HTTP/1.1
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/html
Content-Length: 141

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
Connection closed by foreign host.
```

Server:

```pytb
(tempenv-027621611529f) ~/.v/tempenv-701523535780 $ gunicorn w:f
[2015-05-09 11:53:50 -0400] [75550] [INFO] Starting gunicorn 19.3.0
[2015-05-09 11:53:50 -0400] [75550] [INFO] Listening at: http://127.0.0.1:8000 (75550)
[2015-05-09 11:53:50 -0400] [75550] [INFO] Using worker: sync
[2015-05-09 11:53:50 -0400] [75567] [INFO] Booting worker with pid: 75567
[2015-05-09 11:54:44 -0400] [75567] [ERROR] Error handling request
Traceback (most recent call last):
  File "/Users/alex_gaynor/.virtualenvs/tempenv-027621611529f/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 129, in handle
    req = six.next(parser)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-027621611529f/lib/python2.7/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-027621611529f/lib/python2.7/site-packages/gunicorn/http/message.py", line 153, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-027621611529f/lib/python2.7/site-packages/gunicorn/http/message.py", line 53, in __init__
    unused = self.parse(self.unreader)
  File "/Users/alex_gaynor/.virtualenvs/tempenv-027621611529f/lib/python2.7/site-packages/gunicorn/http/message.py", line 177, in parse
    self.parse_request_line(bytes_to_str(line))
  File "/Users/alex_gaynor/.virtualenvs/tempenv-027621611529f/lib/python2.7/site-packages/gunicorn/http/message.py", line 326, in parse_request_line
    parts = urlsplit(self.uri)
  File "/Users/alex_gaynor/.pyenv/versions/2.7.9/lib/python2.7/urlparse.py", line 214, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

This should result in a 400 bad request, not a 500.

(This was found using the AFL fuzzer)

### PR DESCRIPTION
**Pull request by berkerpeksag**
…alicious data.

Closes #1023

### CODE REVIEW

**Comment by tilgovi** [comment]
```patch
commit e7615093a9bd243cbbb1a1a262ec60fd74b8c338
Author: Randall Leeds <randall@bleeds.info>
Date:   Sat May 9 09:53:17 2015 -0700

    Add test for #1023

diff --git a/tests/requests/invalid/016.http b/tests/requests/invalid/016.http
new file mode 100644
index 0000000..aa08e54
--- /dev/null
+++ b/tests/requests/invalid/016.http
@@ -0,0 +1,2 @@
+PUT ///]ufd/: HTTP/1.1\r\n
+\r\n
diff --git a/tests/requests/invalid/016.py b/tests/requests/invalid/016.py
new file mode 100644
index 0000000..98f43e0
--- /dev/null
+++ b/tests/requests/invalid/016.py
@@ -0,0 +1,3 @@
+from gunicorn.http.errors import InvalidRequestLine
+
+request = InvalidRequestLine
```

**Comment by berkerpeksag** [comment]
Thanks! Weird, it only failed in Python 2.6 :/

**Comment by berkerpeksag** [comment]
Python 2.6 simply does not know anything about IPv6: https://hg.python.org/cpython/file/2.6/Lib/urlparse.py#l173

urlsplit in Python 2.7: https://hg.python.org/cpython/file/2.7/Lib/urlparse.py#l191

Should we backport urlsplit for 2.6 or simply ignore 2.6?

**Comment by asvetlov** [comment]
@berkerpeksag 
Hmm. Good to know.
Unfortunately gunicorn should support the feature until the project declare dropping Python 2.6 at all.
Back-porting is necessary I think.

**Comment by berkerpeksag** [comment]
Done! Travis looks happy now.

**Comment by benoitc** [comment]
shouldn't it be merged?

**Comment by benoitc** [comment]
thanks!

**Pull request merged**
