### PR TITLE
Fix information about Python supported versions

### PR DESCRIPTION
**Pull request by diegoholiveira**

### CODE REVIEW

**Comment by tilgovi** [comment]
Thank you. I don't think we dropped 3.3 support with this release, though.

**Comment by tilgovi** [comment]
Although, we will shortly.

**Comment by tilgovi** [comment]
Maybe that's okay. 3.3 is EOL, so I'm okay with documenting 3.4+, especially because we are about to drop 3.3.

**Comment by tilgovi** [comment]
Well, let's make it accurate, though. We can change it again when we require 3.4+.

**Comment by diegoholiveira** [comment]
@tilgovi I add 3.3 to the supported versions again.

**Comment by tilgovi** [comment]
I should have said 3.2. I don't think we dropped 3.2, yet, either :)

**Comment by tilgovi** [comment]
Thank you, @diegoholiveira! We will want to merge something like this very soon :)

**Comment by tilgovi** [comment]
I'll add 3.7 to the meta for now.

**Pull request closed without merging**
