### PR TITLE
added appier frameworks example

### PR DESCRIPTION
**Pull request by vickysam**
added appier frameworks example.
Appier- An object-oriented Python web framework built for super fast app development.

### CODE REVIEW

**Comment by vickysam** [comment]
added appier frameworks example

**Comment by berkerpeksag** [comment]
Thanks for the pull request! :) I don't think we should add more framework examples. It looks like appier doesn't require any specific configuration for Gunicorn and doesn't seem to be a very popular choice at the moment.

**Comment by vickysam** [comment]
I agree, Thanks :)

**Comment by berkerpeksag** [comment]
If you'd like work on something else, I've just opened https://github.com/benoitc/gunicorn/issues/1346 :) You may want to wait for the feedback of other maintainers before starting to work on it though.

**Comment by vickysam** [comment]
Sure,

I will start working on it.

**Pull request closed without merging**
