### PR TITLE
Drop support for Python 2, 3.2 and 3.3

### PR DESCRIPTION
**Pull request by hugovk**
The last commit drops support for EOL Python 3.2 and 3.3.

Python 3.2 and 3.3 no longer receive security updates (or any updates) from the core Python team and they're little used.

Here's the pip installs for gunicorn from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  45.26% |        307,483 |
| 3.6            |  26.47% |        179,818 |
| 3.5            |  24.62% |        167,242 |
| 3.4            |   3.48% |         23,667 |
| 3.7            |   0.07% |            460 |
| 3.3            |   0.06% |            401 |
| 2.6            |   0.05% |            315 |
| None           |   0.00% |              5 |
| 3.2            |   0.00% |              1 |

Source: `pypinfo --start-date -58 --end-date -28 --percent --pip --markdown gunicorn pyversion`

---

* Also includes "Drop support for Python 2" https://github.com/benoitc/gunicorn/pull/1764:

---

* Continues "[WIP] Delete all Python 2 compatibility code" https://github.com/benoitc/gunicorn/pull/1288, 
* includes "Drop Python 2.6 support" https://github.com/benoitc/gunicorn/pull/1379, 
* for "gunicorn 20" https://github.com/benoitc/gunicorn/issues/1195.

### CODE REVIEW

**Comment by tnir** [comment]
Thanks, I got it.

**Comment by benoitc** [comment]
@tilgovi yes. Let's drop support of 2.7 in next major release.

**Comment by tilgovi** [comment]
I don't have strong opinions on how we branch and manage backports but would like to start doing it soon. If anyone has clear thoughts, open a PR for `CONTRIBUTING.md` any time and I'll leave any comments I have. We can get a release branching policy and maintenance policy in place even before we drop any Python versions. Once we have the branches, it'll be easier to apply and know where to apply these PRs.

**Comment by hugovk** [comment]
@berkerpeksag Please see PR https://github.com/benoitc/gunicorn/pull/1839 to drop support for EOL Python 3.2 and 3.3 only.

**Pull request closed without merging**
