### PR TITLE
Add accesslog params

### PR DESCRIPTION
**Pull request by bungoume**
I would like to add accesslog params like Apache.
If you do not mind, please merge.

ref: http://httpd.apache.org/docs/current/mod/mod_log_config.html

### CODE REVIEW

**Comment by benoitc** [comment]
i like the idea, however the tests don't pass right now. Seems PATH_INFO doesn't exist during the tests. Can you fix it ?

**Comment by bungoume** [comment]
Oh sorry, I'll fix it.

**Comment by bungoume** [comment]
Fixed. Could you review?

**Comment by tilgovi** [comment]
LGTM

**Pull request merged**
